const tables = [
  `DROP TABLE IF EXISTS userChannel`,
  `DROP TABLE IF EXISTS channel`,
  `DROP TABLE IF EXISTS user`,

  `CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (id),
    UNIQUE INDEX email (email),
    UNIQUE INDEX username (username)
  )`,

  `CREATE TABLE channel (
    id INT NOT NULL AUTO_INCREMENT,
    authorId INT NOT NULL,
    channelName VARCHAR(30) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    UNIQUE INDEX channelName (channelName),
    PRIMARY KEY (id),
    CONSTRAINT fk_author FOREIGN KEY (authorId) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
  )`,

  `CREATE TABLE userchannel(
    userId INT NOT NULL,
    channelId INT NOT NULL,
    PRIMARY KEY (userId, channelId),
    CONSTRAINT fk_user FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_channel FOREIGN KEY (channelId) REFERENCES channel(id) ON DELETE CASCADE ON UPDATE CASCADE
  )`,
];

export default tables;
